### ISSUE TITLE
Possible issue with Logging actuator

### ISSUE THREAD

**Issue by Jason01450** [SteeltoeOSS/Management#1]
We deployed the latest (from dev branch) Management sample app to PWS. We built, published, and tested this using the provided nuget.config configured Steeltoe library. We also built, published, and tested this using the latest (dev) version of Steeltoe (3 assemblies were newer). In both cases, when run, the app always logs 5 of the 6 (excluding the Trace) test log messages into the logs regardless of how the app's logging level is configured. We observed that the app is receiving the /loggers POST and GET from the App Manager. We did not observe any obviously related errors in the logs.

**Comment by TimHess** [comment]
Hi @Jason01450, sorry about the slow response, we're trying to get an RC out for 2.0 and it also looks like the trigger to kick this over to our Tracker didn't fire. Were you adjusting the log levels via Apps Manager at runtime, or changing the configs and redeploying?

**Comment by Jason01450** [comment]
HI Tim, thanks for the reply. We were adjusting the logging levels via Apps Manager. The goal of the exercise was to demo changing the logging level and seeing the change take effect.

**Comment by dtillman** [comment]
Hi @Jason01450 ,
I'm trying to recreate the issue you're reporting .. but having problems doing so.  

It could be that I'm testing using the latest bits which we are planning to release as 2.0 Final and as a result we have fixed the issue you have seen. 

Would you be willing to try your test again... pull the Management sample from the dev branch and try and push it again and verify you are still seeing the problem.

Thanks!
Dave

**Comment by dtillman** [comment]
Closing this , feel free to reopen if you are still seeing this.
Dave
