### ISSUE TITLE
Steeltoe.Management.Endpoint.Loggers.LoggersEndpoint not overridable

### ISSUE THREAD

**Issue by dwilliss** [SteeltoeOSS/Management#15]
The Loggers endpoint takes an ILoggerProvider and then tries to cast it to a DynamicLoggerProvider.  

Could this possibly be changed to cast to an **I**DynamicLoggerProvider _interface_ so we could inject in a custom one?

**Comment by dtillman** [comment]
Thanks @dwilliss ... change is available on dev feed and will be included in next service release for 2.1

**Comment by dwilliss** [comment]
Thanks!

**Comment by dwilliss** [comment]
Any idea when the next service release of 2.1 will be?

**Comment by jkonicki** [comment]
@dwilliss We should have the release of 2.1.1 out this week.

**Comment by dwilliss** [comment]
Yay!  That worked.... Something is creating a logger named Steetoe though.  I don't see that in a global search of any of my code.  

![image](https://user-images.githubusercontent.com/1755696/46975099-5cc13e80-d08b-11e8-8077-c34cbb49f355.png)
