### ISSUE TITLE
Info Endpoint ignored by Apps Manager

### ISSUE THREAD

**Issue by dwilliss** [SteeltoeOSS/Management#16]
This should maybe be an Issue for Pivotal Apps Manager, but I can't find where to report an issue for that.  If so, somebody please point me in the right direction.

The /cloudfoundry/info endpoint doesn't seem to do anything.  I added an IInfoContributor, and I can see from traces that it's getting called, and the trace says that the request is giving a 200 response code.  But no additional information shows up in the Status pane's Info section like the documentation says it will.

It was suggested that we add a git.properties file to the project and publish that.  We don't use git for source control, so we don't have one, but I tried creating one with a single property (`git.foo=bar`) project and publishing that.  The results were quite surprising. When I pull up the app in Apps Manager, the screen just shows this:

![image](https://user-images.githubusercontent.com/1755696/46297467-58ad0100-c562-11e8-9302-b8aa9ac509ed.png)

So questions:  
1) What is it actually looking for in this file?  I can't find an example of one.  Google wants to show me entries about git.config.
2) Even without this file being present, why does it ignore the endpoint I gave it?  We have a theory that it's looking for a specific property in the response and if it doesn't find it, just ignoring the whole thing.

**Comment by TimHess** [comment]
The tracker for Apps Manager is private, I'm not positive on exactly how you'd need to submit requests to them, but I imagine it would be via Pivotal Support.

The issue was resolved in their tracker with a code change back in mid-August, but I don't have access to the source to know specifically how they resolved it, and I'm not positive what version of PCF you'd need to have that fix.

Its possible that specific exception is due to the absence of commit information in the response. As a short-term workaround, you could just add all of these properties:
```
git.commit.id=765c615f234a745f68330aa0ac39d980f80c9191
git.remote.origin.url=C:\steeltoe\samples\
git.build.version=1.1.0
git.commit.id.abbrev=765c615
git.tags=
git.branch=dev
git.build.time=2018-08-20T14:04:12.4455941-05:00
git.build.user.name=thess
git.build.host=DESKTOP-KML5IH5
```
You could also work through the properties individually if you want to (it may only be `git.commit.id` that is needed), I don't know offhand what else would be required.

If this workaround doesn't work and/or you can't go through support to get an answer on the Apps Manager version, let me know and I can use other channels to get more info.

**Comment by dwilliss** [comment]
That worked -- sort of.  It shows _some_ of the information in that file but still ignores the results from my IInfoContributor (the application.version).   I can see it in the raw JSON, but it's not shown normally.
![image](https://user-images.githubusercontent.com/1755696/46303946-e7297e80-c572-11e8-96f0-adf3da334de5.png)

```
{
  "application": {
    "version": "this is a test"
  },
  "git": {
    "branch": "dev",
    "build": {
      "host": "DESKTOP-KML5IH5",
      "time": 1534791852445,
      "user": {
        "name": "thess"
      },
      "version": "1.1.0"
    },
    "commit": {
      "id": "765c615f234a745f68330aa0ac39d980f80c9191"
    },
    "remote": {
      "origin": {
        "url": "C:\\steeltoe\\samples\\"
      }
    },
    "tags": ""
  }
}
```
I'm not sure what version of Apps Manager we have, but the Docs tab gives me docs for version 2.3, so I assume that's what we have.

**Comment by TimHess** [comment]
The best way to check that I know is to match the version on the PAS tile in Ops Manager against the release notes for PAS -- the 2.1 line lives here: https://docs.pivotal.io/pivotalcf/2-1/pcf-release-notes/runtime-rn.html

There are a couple recent items related to Steeltoe apps, but I don't know for sure this one is one of them. It looks likes the Tracker story has not been accepted yet, but I've reached out to the Apps Manager team for clarification. There is a chance that the item `Fix Spring “View Raw JSON” feature not appearing when git info not present on app` under 2.1.13 is actually talking about this bug

**Comment by TimHess** [comment]
@dwilliss can you confirm the specific (patch) version of PAS in your foundation?

**Comment by dwilliss** [comment]
It looks like we're on 2.1.12.  I'll have to get them to upgrade us.

**Comment by dwilliss** [comment]
I was told that we have a "sandbox" environment with 2.1.14 installed.  It doesn't have some other stuff we need like Vault, but I as able to push up a small test app to test this.
With 2.1.14, I no longer need a git.properties file.  I can return the git information myself.

It still only shows the fields from my provider in the Raw JSON, and won't show the one field from git that I **_want_** it to show (Version) on the main Settings screen.  You have to look at the Raw JSON for that too.

**Comment by dwilliss** [comment]
I would like to see this as a future enhancement (not an issue).  It would be nice if the application could implement an IInfoProvider and use that to put custom information on the Apps Manager screen.

If nothing else, I'd like to see Apps Manager show the build version from the Git provider that already exists.  We solved our immediate need by repurposing the git.commit.id.abbrev which it _does_ show to be the version number. 
![image](https://user-images.githubusercontent.com/1755696/46542720-bbfda280-c884-11e8-89f6-6c73725f1504.png)

**Comment by pivotal-mikegresham** [comment]
@dwilliss is version the only thing thats missing? is there any other info from the git & build json you'd like to see? how about the format/organization - does it make sense currently or are there changes you'd like to see?

**Comment by dwilliss** [comment]
Version is the main one I'd like to see.  Having it in the upper right corner of the screen where the Git: version is now would be ***awesome***.  

Having some way to specify arbitrary fields in the IInfoContributor would be a cool feature too. I don't know how you could do that though.  Maybe something like allowing a value in the Json to be either a string or a name/value pair like this:

```
{
  "application": {
    "version": {
         "label": "Version",
         "value": "6.0.5.1",
         "some-awesome-flag-to-make-it-show-up-at-top-of-screen": true
         }
  }, 
  _other stuff_
}
```

I don't know, that's just a wild idea.  You can probably come up with something better and still be backwards compatible.
