### ISSUE TITLE
Overrides span-id coming from PCF GoRouter

### ISSUE THREAD

**Issue by keyurpd** [SteeltoeOSS/Management#18]
The library is good. But I observed that it overrides span-id coming from GoRouter on PCF.

From GoRouter log: `x_b3_traceid:"edc53528d9f6dfb6" x_b3_spanid:"edc53528d9f6dfb6" x_b3_parentspanid:"-"`
From app log: `[my-app,edc53528d9f6dfb6,b5bbb621fc6fff11,3337e895d451fbae,true] Critical message`

Also, what is `3337e895d451fbae`?

**Comment by dtillman** [comment]
@keyurpd: Yes, we start a new span, as part of the incoming traceid on entry.   Keep in mind that the Go Router does not forward spans anywhere (i.e. to a zipkin server), so the spanids it generates will never find there way into a zipkin server.

In the example above  3337e895d451fbae should be the parent span id of the b5bbb621fc6fff11 span.

Hope that helps.

Dave

**Comment by keyurpd** [comment]
Thank you for the response.

1. Considering the GoRouter and the App participating in one network call, shouldn't `edc53528d9f6dfb6` be the parent-span-id for the App?
2. If `3337e895d451fbae` is really the parent span for the app, where did it originate?

**Comment by keyurpd** [comment]
OK.
So seems there is something I missed in the middle of two logs that I observed.
`3337e895d451fbae` might be coming from there, thanks!

**Comment by keyurpd** [comment]
On a related note: Will this work with Istio when it gets integrated in PCF?

**Comment by dtillman** [comment]
@keyurpd : TBD on Istio...

Dave

**Comment by keyurpd** [comment]
Thank you!
