### ISSUE TITLE
Using Cloud Foundry Actuators Crashes without Dynamic Console Logger

### ISSUE THREAD

**Issue by brianuol** [SteeltoeOSS/Management#19]
After upgrading to `Steeltoe.Management.CloudFoundryCore` v 2.1.1, we've observed application crashes on startup due to missing registration for IDynamicLoggerProvider:

`Unable to resolve service for type 'Steeltoe.Extensions.Logging.IDynamicLoggerProvider' while attempting to activate 'Steeltoe.Management.Endpoint.Loggers.LoggersEndpoint'.'`

The above occurs if we include a call to `services.AddCloudFoundryActuators(configuration)` in our startup's `ConfigureServices` method.  In other words, we cannot use the Actuators without using the Dynamic Logger.

Since scoped logging does not currently work with the Dynamic Console Logger we've oped not to use that logger.

**Comment by dtillman** [comment]
@brianuol 
Hi, if you do not want to use the logging actuator, but want to use all of the others that are provided as part of AddCloudFoundryActuators(configuration) .. then you will want to add the ones you really want individually.  The AddCloudFoundryActuators(configuration) is a convenience method that adds all of those that are compatible with CloudFoundry Apps Manager(including Logger).  It assumes you want to use the Loggers Actuators and expects the DynamicLogger to be in the container (i.e. configured).  In 2.1.1 it fails fast if what you said you wanted is not actually whats configured.

So the simple way to add just what you want is just replicate the code from the two methods linked below.  Put it some place in your code and remove what you don't want. (i.e.  AddLoggersActuator() and UseLoggerActuator() methods).

In 2.1.0 and previous versions we simply ignored that there was no DynamicLogger configured even though you had added the LoggerActuater .. the net result was some would forget to add the DynamicLogger and find that they couldn't change logging levels .. or we also had a problem if you added multiple logger providers (e.g.. DynamicProvider and DebugProvider), then sometimes the LoggerActuator would get injected with the wrong one and would unexpectedly not work.  So in 2.1.1 we fixed that... and we now fail fast so you can find and fix the issue.

Also, I will take a look at why scoped logging does not currently work with the Dynamic Console Logger and see if I can fix that.

Have a look at these two methods: 

[AddCloudFoundryActuators()](https://github.com/SteeltoeOSS/Management/blob/dev/src/Steeltoe.Management.CloudFoundryCore/CloudFoundryServiceCollectionExtensions.)
[UseCloudFoundryActuators()](https://github.com/SteeltoeOSS/Management/blob/dev/src/Steeltoe.Management.CloudFoundryCore/CloudFoundryApplicationBuilderExtensions.cs)
