### ISSUE TITLE
Difference between AddHealthActuator() and AddCloudFoundryActuators()

### ISSUE THREAD

**Issue by keyurpd** [SteeltoeOSS/Management#22]
One thing that I observed between `AddHealthActuator()` and `AddCloudFoundryActuators()`

`AddHealthActuator()`
The /health endpoint is without security i.e. anonymous. And status=UP doesn't show up in built-in PCF dashboard.

`AddCloudFoundryActuators()`
The /health endpoint is secured with OAuth token. And status=Up checks show up in PCF dashboard.

Also, is it possible to enable/disable security through code/configuration, while maintaining status checks (green up arrows) within PCF dashboard in both cases?

[Spring Boot Documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-health)

**Comment by TimHess** [comment]
Assuming the PCF dashboard you're referring to is Pivotal Apps Manager, the way it knows how to find the health endpoint (and any other actuator endpoint) in a Steeltoe-enabled app is from the CloudFoundry endpoint's response (`/cloudfoundryapplication`).

In the current state of Steeltoe Management, the security middleware that you're referring to is controlled by the same on/off switch as the CloudFoundry actuator. It is possible to turn off security, but at the expense of also turning off the piece that allows the Apps Manager integration to work.

For Steeltoe 2.2, we are planning to enhance Management to be compatible with Spring Boot 2.0, including changes to the way the security middleware works with regard to this big on/off switch, but that could be a couple months away as we haven't started on it yet.

For an immediate solution, you could roll your own version of [`.UseCloudFoundryActuators()`](https://github.com/SteeltoeOSS/Management/blob/dev/src/Steeltoe.Management.CloudFoundryCore/CloudFoundryApplicationBuilderExtensions.cs) that does not use the security middleware at all.

As an intermediate solution, we could add a discrete switch for the Security middleware, but that might be a bit of a sledgehammer approach. If you'd like this done, it shouldn't be much effort, but I wouldn't do the work without an actual request that its what you wanted.

Does that help?

**Comment by keyurpd** [comment]
I am reading your comment, "*It is possible to turn off security, but at the expense of also turning off the piece that allows the Apps Manager integration to work*". I guess, this is what I observed.

I also played with `requiredPermission` attribute of Steeltoe. But, setting it to NONE doesn't disable Pivotal Apps Manager OAuth based security. Maybe it's a different thing.

I would stick to the standards, instead of a sledgehammer, or even a short-term thing.
Example, (as a developer) following the Spring Boot documentation, finding an appropriate attribute within Steeltoe (or Apps Mgr), and finally getting/observing what the standard says in action.

Thank you!

**Comment by hananiel** [comment]
In the upcoming 2.2 release there are two features that help resolve this issue. PR #40 lets you add a Discovery endpoint that helps expose the health(and/or other) endpoints independent of apps manager integration. #41 Allows you to show hide details based on configuration - by default you should be able to see the up/down feature in apps manager or another app of your choice. In the mean time I would love your feedback on this.

**Comment by hananiel** [comment]
Closing this issue for now. We can reopen if needed.

**Comment by keyurpd** [comment]
Nice! I will try it out on the next available opportunity. Thank you.
