### ISSUE TITLE
The zipkin traceid and spanid doesnt seem to be getting propagated automatically.

### ISSUE THREAD

**Issue by deepuvikraman** [SteeltoeOSS/Management#37]
The zipkin traceid and spanid doesnt seem to be getting propagated automatically.
Below is my scenario:
I have a .netcore 2.1 webapplication that calls a .netcore webapi (service1) which then calls service2. Traceid is getting propagated from applicaiton to service1.But from service1 to service2, it is not propagated. When I check the logs in service2, it has a new traceid
Sample logs:
from application - x_b3_traceid:"26855fde01535887" x_b3_spanid:"26855fde01535887" x_b3_parentspanid:"-"
from service1 - x_b3_traceid:"26855fde01535887" x_b3_spanid:"711fe2a898a5c207" x_b3_parentspanid:"76a4df594ef37e19"
from service2 - x_b3_traceid:"2e9a98636bae5474" x_b3_spanid:"2e9a98636bae5474" x_b3_parentspanid:"-"

I am using the Steeltoe.Management.TracingCore 2.1.1 package. the sample application in steeltoe gitrepo(https://github.com/SteeltoeOSS/Samples/tree/dev/Management/src/AspDotNetCore/Tracing) is using a package version 2.2.0-dev-00338 which is not avaiable in nuget

Any pointers?

**Comment by dtillman** [comment]
@deepuvikraman: 

You have added distributed tracing to Service1 right?

Not sure what is going on... I went ahead and confirmed it works using the Steeltoe 2.2-RC2 bits.

Here is a sample that I ran locally.. I just run a zipkin server locally (via docker) and it all seems to work.

https://github.com/dtillman/TracingSample.git

I'm going to close this .. but feel free to reopen if the sample doesn't help.

Dave
