### ISSUE TITLE
Add in ability to easily turn off OAuth based security when integrating with Cloud Foundry

### ISSUE THREAD

**Issue by mikegehard** [SteeltoeOSS/Management#6]
Given I have an application integrated with PCF Apps Manager via the docs
When I set some sort of environment variable locally (maybe DISABLE_MANAGEMENT_AUTH)
Then I can access the management endpoints without needing an OAuth token

Motivation: I want to check my endpoints via curl (or some other raw HTTP call).

Currently, I have to  look for an environment variable and then duplicate the logic in the `UseCloudFoundryActuators()` extension method if that environment variable is set. Can be a little brittle.

**Comment by dtillman** [comment]
Thanks Mike... makes sense.
We'll add something in the upcoming release.
Dave

**Comment by mikegehard** [comment]
Thanks @dtillman.

**Comment by TimHess** [comment]
https://github.com/SteeltoeOSS/Management/commit/a8eda8364aaf465548a9e52d49092ce6e86b91a6
