### ISSUE TITLE
Actuators issue when Authorisation mechanism is used within the app

### ISSUE THREAD

**Issue by JuanGarciaCarmona** [SteeltoeOSS/Management#7]
Hi, I speak on behalf my current Dev Team.

The company is using PCF and my team and I are publishing few applications using SteelToe libraries to grab configuration and to use actuators from Apps Manager. In general we are very happy with the results (thanks and congrats by the way) but one of them, a small API that enforces authentication and authorisation with JWT, is giving issues from Apps Manager since its very first deployment.  The issue, after a long research, seems to be related with that the app, at the end, is having two auth mechanisms, the one that we are using and the one that the actuators uses internally to allow PCF to access the actuators endpoints. 

The only way we found to make everything works was to forget about actuators so that we can't change log level at run time or access the health endpoint to give an example. Are there any other teams authorising their controllers and aiming to, also, use actuators from Apps Manager having similar issues?

KR;

Juan

**Comment by TimHess** [comment]
Can you clarify for me which of these are happening when actuators and your app security are both enabled?
- Apps manager can't reach actuators
- Application security does not work as expected

The security that is applied to actuator endpoints is only applied on requests where the path starts with /cloudfoundryapplication, so it shouldn't interfere with other requests (unless your application also uses that path for some requests).

**Comment by JuanGarciaCarmona** [comment]
Hi and thanks for your quick response.

First thing is happening, Apps manager can't reach actuators so that app managment view becomes unusable due to a lot of JavaScript errors, looking at those actuators url's directly we get a wrong authorisation headers error.

Thank you!

**Comment by TimHess** [comment]
Ok, I think that makes sense. I'm guessing your app's security is being applied on every request, no matter the route. I would be a bit surprised if there is a way for Apps Manager to do custom authentication with your application, as far as I know the only thing it will do is pass your (as the user logged into Apps Manager) bearer token to the application. Steeltoe's security checks those tokens against the same cloud controller that you used to login to Apps Manger.

In Steeltoe 2.1 (available on the MyGet dev feed) you can disable the security on the actuators, which would enable you to browse to them directly, but that won't fix Apps Manager not being able to reach them.

My recommendation is to alter your app's security mechanism to ignore requests that look like `/cloudfoundryapplication*`. To make requests against the actuators directly, we normally use either curl or Postman

**Comment by JuanGarciaCarmona** [comment]
Well, yes, we decide wich controllers will use security mechanism by using [Autorize] attribute, probably the same attribute that your endpoints are using internally in your code, am I right? If this is the case then we'll be forced to forget on actuators, at least from Apps Manager.

**Comment by TimHess** [comment]
The actuators are not built with controllers, they're built as middleware, so we don't use `[Authorize]`. I think something with your application's security may be applying overly-broadly, this is not expected behavior.

Are you able to put together a sample that you could share that reproduces the issue?

**Comment by dtillman** [comment]
@JuanGarciaCarmona
As Tim mentioned, the actuator endpoints are implemented as middleware in the pipeline... and of course as you are aware ... order matters...  so its important that they be added very early on in the middleware pipeline... 

Can you confirm that they are added "first" ... (i.e. like the  Sample) ... before MVC?

Dave

From Management Sample:  https://github.com/SteeltoeOSS/Samples/blob/dev/Management/src/AspDotNetCore/CloudFoundry/Startup.cs

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            // Add management endpoints into pipeline
            app.UseCloudFoundryActuators();

            app.UseMvc(routes =>
            {
......
            }

**Comment by JuanGarciaCarmona** [comment]
To @TimHess : I'll work on the sample, I'll give you tThe URL as soon as I have it. 

To @dtillman : Yes, order matters and the` app.UseCloudFoundryActuators()`; is before 

`app.UseJwtSimpleServer(setup =>
{
    setup.IssuerSigningKey = SigningKey;
});
`

By the way, the sec mechanism we are using is JWTSimpleServer which repository is here: https://github.com/Xabaril/JWTSimpleServer

**Comment by JuanGarciaCarmona** [comment]
I have good and bad news:

The good news:
I created a sample project, very basic but quite complete, with Swagger, JWTSimpleServer and few controllers, Home (that redirects to swagger); Unauthorised, that allows every request, and Authorised, that enforces security. Simple, easy, but useful, it could be used as an starting point sample I'd say... The repository is here: [SampleJwtSimpleServerPCF](https://github.com/JuanGarciaCarmona/SampleJwtSimpleServerPCF)

The bad news :
It works as expected in PCF. So, well, those are bad news for me... I'll try to find what is making the problematic project unstable and I'll let you know what I can find out.

Which are the differences between the working sample and the problematic project?

- Sample doesn't grab configuration (first thing I'll try)
- Sample does not use other services like RabbitMQ or Reddis  (Second and Third attempt)
- Less dependencies (solved with NuGet in the problematic project) so less services and less service configurations... (Next attempts will be focused here)

Final words:
- I hope you find my sample useful, fell free to use it or share it
- I'll close the issue tomorrow, no matter if I find the source or not, because the issue seems to be on our side.
- Thanks a lot for your help.

KR,


Juan

**Comment by JuanGarciaCarmona** [comment]
Again, thank you.

I close the issue and I'll only reopen if we find out that it might be related with Your (very helpful) libraries.

KR,

Juan
